server:
  port: 8082
spring:
  servlet:
    multipart:
      max-file-size:
        200MB
      max-request-size:
        200MB

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: UPLOAD-SERVICE

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

jd:
  media:
    path:
      demo: F:\IntelliJProjects\uploadPath\demo
      lectures: F:\IntelliJProjects\uploadPath\lectures

